/**
 * One-time SQLite -> Railway Postgres importer.
 *
 * Usage:
 *   DATABASE_URL=... DB_PATH=/data/shepherd.db npx tsx server/migrations/000_initial_from_sqlite.ts
 *
 * This script is deliberately idempotent: destination inserts use
 * ON CONFLICT DO NOTHING and sequences are advanced after copy. Take a Railway
 * backup and copy the SQLite volume before running it.
 */
import Database from "better-sqlite3";
import PgPool from "pg-pool";
import { existsSync } from "fs";
import { randomBytes } from "crypto";
import bcrypt from "bcryptjs";

const DB_PATH = process.env.DB_PATH || "shepherd.db";
const DATABASE_URL = process.env.DATABASE_URL;

const schema = `
CREATE TABLE IF NOT EXISTS churches (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, location text NOT NULL DEFAULT '', denomination text NOT NULL DEFAULT '', logo_url text NOT NULL DEFAULT '', primary_color text NOT NULL DEFAULT '#7B4A1E', sendgrid_api_key text NOT NULL DEFAULT '', sendgrid_from_email text NOT NULL DEFAULT '', sendgrid_list_id text NOT NULL DEFAULT '', sendgrid_sender_id text NOT NULL DEFAULT '', sendgrid_provisioned_at text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS members (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer NOT NULL REFERENCES churches(id), first_name text NOT NULL, last_name text NOT NULL, email text NOT NULL, phone text NOT NULL DEFAULT '', segment text NOT NULL DEFAULT 'new_visitor', joined_at text NOT NULL, last_engaged text NOT NULL, notes text NOT NULL DEFAULT '', home_zip text NOT NULL DEFAULT '', sendgrid_contact_id text NOT NULL DEFAULT '', unsubscribed_at text NOT NULL DEFAULT '', bounce_count integer NOT NULL DEFAULT 0, engagement_segment text NOT NULL DEFAULT 'new', deactivated_at text NOT NULL DEFAULT '', deactivation_reason text NOT NULL DEFAULT '', is_donor integer NOT NULL DEFAULT 0, donor_since text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS campaigns (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer NOT NULL REFERENCES churches(id), name text NOT NULL, type text NOT NULL, subject text NOT NULL, preview_text text NOT NULL DEFAULT '', body_html text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', scheduled_at text, sent_at text, recipients integer NOT NULL DEFAULT 0, opens integer NOT NULL DEFAULT 0, clicks integer NOT NULL DEFAULT 0, bible_topic_tag text NOT NULL DEFAULT '', meta text NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS sequences (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer NOT NULL REFERENCES churches(id), name text NOT NULL, trigger_segment text NOT NULL, status text NOT NULL DEFAULT 'active', step_count integer NOT NULL DEFAULT 0, enrolled_count integer NOT NULL DEFAULT 0, completed_count integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS activities (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer NOT NULL REFERENCES churches(id), type text NOT NULL, description text NOT NULL, created_at text NOT NULL, meta text NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS insights (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer REFERENCES churches(id), topic text NOT NULL, question text NOT NULL DEFAULT '', session_id text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', verse_ref text NOT NULL DEFAULT '', verse_text text NOT NULL DEFAULT '', reflection text NOT NULL DEFAULT '', created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS affiliations (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id text NOT NULL, church_id integer NOT NULL REFERENCES churches(id), first_name text NOT NULL DEFAULT '', email text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS app_users (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL UNIQUE, name text NOT NULL DEFAULT '', google_id text DEFAULT '', magic_token text DEFAULT '', magic_expiry text DEFAULT '', church_id integer REFERENCES churches(id), home_church_name text, zip_code text, is_test_user integer NOT NULL DEFAULT 0, tier text NOT NULL DEFAULT 'free', created_at text NOT NULL, last_login_at text NOT NULL);
CREATE TABLE IF NOT EXISTS chats (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL REFERENCES app_users(id), topic text NOT NULL, question text NOT NULL DEFAULT '', verse_ref text NOT NULL DEFAULT '', verse_text text NOT NULL DEFAULT '', reflection text NOT NULL DEFAULT '', created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS bible_topic_content (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, topic text NOT NULL, verse_ref text NOT NULL DEFAULT '', verse_text text NOT NULL DEFAULT '', reflection text NOT NULL DEFAULT '', rotation_order integer NOT NULL DEFAULT 0, active integer NOT NULL DEFAULT 1, created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS sequence_enrollments (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer NOT NULL REFERENCES churches(id), member_id integer NOT NULL REFERENCES members(id), sequence_type text NOT NULL DEFAULT 'onboarding', current_step integer NOT NULL DEFAULT 0, last_sent_at text NOT NULL DEFAULT '', started_at text NOT NULL, completed_at text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS email_events (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, church_id integer REFERENCES churches(id), member_id integer REFERENCES members(id), sendgrid_contact_id text NOT NULL DEFAULT '', sendgrid_message_id text NOT NULL DEFAULT '', email text NOT NULL, event_type text NOT NULL, url text NOT NULL DEFAULT '', reason text NOT NULL DEFAULT '', campaign_id text NOT NULL DEFAULT '', occurred_at text NOT NULL, raw_payload text NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS chat_reactions (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL REFERENCES app_users(id), chat_id integer NOT NULL REFERENCES chats(id), reaction text NOT NULL, created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS donation_prompts (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL REFERENCES app_users(id), trigger text NOT NULL, outcome text NOT NULL DEFAULT 'shown', shown_at text NOT NULL, outcome_at text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS donations (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer REFERENCES app_users(id), email text NOT NULL DEFAULT '', stripe_session_id text NOT NULL UNIQUE, stripe_payment_intent_id text NOT NULL DEFAULT '', amount_cents integer NOT NULL, currency text NOT NULL DEFAULT 'usd', frequency text NOT NULL DEFAULT 'one_time', status text NOT NULL DEFAULT 'pending', prompt_id integer REFERENCES donation_prompts(id), created_at text NOT NULL, completed_at text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS member_signups (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL UNIQUE, zip_code text NOT NULL, user_id integer REFERENCES app_users(id), home_church_name text, source text NOT NULL DEFAULT 'app_first_visit_modal', ip_address text NOT NULL DEFAULT '', user_agent text NOT NULL DEFAULT '', created_at text NOT NULL, updated_at text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS traffic_snapshots (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source text NOT NULL, metric text NOT NULL, value integer NOT NULL, recorded_at text NOT NULL, note text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS crisis_safety_signals (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer REFERENCES app_users(id), session_id text, category text NOT NULL, created_at text NOT NULL);
CREATE TABLE IF NOT EXISTS curated_questions (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, admin_user_id text NOT NULL, question_id integer NOT NULL REFERENCES insights(id), created_at text NOT NULL, UNIQUE(admin_user_id, question_id));
CREATE TABLE IF NOT EXISTS daily_question_counts (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL REFERENCES app_users(id), date text NOT NULL, count integer NOT NULL DEFAULT 0, created_at text NOT NULL, updated_at text NOT NULL, UNIQUE(user_id, date));
CREATE TABLE IF NOT EXISTS admin_users (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email text NOT NULL UNIQUE, password_hash text NOT NULL, role text NOT NULL DEFAULT 'admin', created_at text NOT NULL, last_login_at text, is_active integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS auth_refresh_tokens (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, token_hash text NOT NULL UNIQUE, subject_type text NOT NULL, subject_id integer NOT NULL, expires_at text NOT NULL, revoked_at text, created_at text NOT NULL);
CREATE INDEX IF NOT EXISTS idx_chats_user_created ON chats(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_daily_question_counts_user_date ON daily_question_counts(user_id, date);
CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);
CREATE INDEX IF NOT EXISTS idx_donations_user_created ON donations(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_crisis_safety_signals_created ON crisis_safety_signals(created_at);
`;

const tables = [
  "churches", "members", "campaigns", "sequences", "activities", "insights", "affiliations", "app_users",
  "chats", "bible_topic_content", "sequence_enrollments", "email_events", "chat_reactions", "donation_prompts",
  "donations", "member_signups", "traffic_snapshots", "crisis_safety_signals", "curated_questions",
  "daily_question_counts", "admin_users", "auth_refresh_tokens",
];

async function main() {
  if (!DATABASE_URL) throw new Error("DATABASE_URL is required");
  const pool = new PgPool({ connectionString: DATABASE_URL, max: 20 });
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(schema);
    if (existsSync(DB_PATH)) {
      const sqlite = new Database(DB_PATH, { readonly: true });
      for (const table of tables) {
        const exists = sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table);
        if (!exists) continue;
        const rows = sqlite.prepare(`SELECT * FROM "${table}"`).all() as Array<Record<string, unknown>>;
        for (const row of rows) {
          const fields = Object.keys(row);
          if (!fields.length) continue;
          const placeholders = fields.map((_, index) => `$${index + 1}`).join(", ");
          await client.query(
            `INSERT INTO "${table}" (${fields.map(field => `"${field}"`).join(", ")}) VALUES (${placeholders}) ON CONFLICT DO NOTHING`,
            fields.map(field => row[field]),
          );
        }
        if (rows.length) {
          await client.query(`SELECT setval(pg_get_serial_sequence('"${table}"', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM "${table}"), 1), true)`);
        }
      }
      sqlite.close();
    } else {
      console.log(`[migration] SQLite file not found at ${DB_PATH}; created empty PostgreSQL schema.`);
    }
    const existing = await client.query("SELECT id FROM admin_users LIMIT 1");
    if (!existing.rowCount) {
      const password = randomBytes(24).toString("base64url");
      await client.query(
        "INSERT INTO admin_users (email, password_hash, role, created_at, is_active) VALUES ($1, $2, 'owner', $3, 1)",
        ["ryan@myshepherdapp.church", bcrypt.hashSync(password, 12), new Date().toISOString()],
      );
      console.log(`[security] Initial admin password for ryan@myshepherdapp.church: ${password}`);
    }
    await client.query("COMMIT");
    console.log("[migration] PostgreSQL schema and SQLite data migration complete.");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch(error => {
  console.error("[migration] failed", error);
  process.exitCode = 1;
});
